module.exports = {
    'PORTPOLIO': 'PORTPOLIO',
    'INQUIRY': 'BOARD_INQUIRY',
    'COMMENT_INQUIRY': 'COMMENT_INQUIRY',
    'BOARD_NOTICE': 'BOARD_NOTICE',
    'BOARD_REVIEW': 'BOARD_REVIEW',
    'GK_USERS': 'GK_USERS'
}
